package model

// Alert is generated by the Nagger agent.
type Alert struct {
	Type        string  `json:"type"`                  // "warning", "impulse_flag", "luxury_drift"
	Message     string  `json:"message"`
	Category    string  `json:"category,omitempty"`
	Amount      float64 `json:"amount,omitempty"`
	CategoryAvg float64 `json:"category_avg,omitempty"`
}

// Recommendation is generated by the Strategist agent.
type Recommendation struct {
	Title                string  `json:"title"`
	Description          string  `json:"description"`
	EstimatedMonthlySave float64 `json:"estimated_monthly_save"`
	Priority             string  `json:"priority"` // "high", "medium", "low"
}
